module.exports = {
  semi: false,
  singleQuote: true,
  printWidth: 100,
  trailingComma: 'es5',
  arrowParens: 'always',
  tabWidth: 2,
  useTabs: false,
  quoteProps: 'as-needed',
  jsxSingleQuote: false,
  bracketSpacing: true,
  bracketSameLine: false,
  importOrder: [
    '^(next(.*)$)',
    '^(react(.*)$)',
    '<THIRD_PARTY_MODULES>',
    '^@/components/(.*)$',
    '^@/data/(.*)$',
    '^@/hooks/(.*)$',
    '^@/services/(.*)$',
    '^@/styles/(.*)$',
    '^@/types/(.*)$',
    '^@/utils/(.*)$',
    '^[./]',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrderGroupNamespaceSpecifiers: true,
  tailwindFunctions: ['cn', 'cva', 'clsx'],
  plugins: ['@trivago/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss'],
}
